language: ruby
cache: bundler
sudo: false
rvm:
- 2.1
matrix:
    include:
        - rvm: 2.1
          env: JEKYLL_VERSION=2.4
    fast_finish: true

# branch whitelist, only for GitHub Pages
branches:
    only:
        - gh-pages

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
install:
    - travis_retry script/bootstrap

script: script/cibuild

env:
    global:
        - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
