language: ruby
rvm:
  - 2.1
matrix:
    include:
        - rvm: 2.1
          env: JEKYLL_VERSION=3.03
    fast_finish: true
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
cache: bundler
sudo: false
before_script: bundle update
script: script/cibuild
branches:
  only:
    - gh-pages
