url: http://sudweb.fr/2016
name: Sud Web 2016, Bordeaux
description: Deux journées pour faire le plein d'inspiration, les 27 et 28 mai 2016 à Bordeaux.
baseurl: /2016
permalink: /:title/
paginate: 5
timezone: Europe/Paris
sass:
    sass_dir: _sass
google_analytics_id: UA-22076213-1
