# Site configuration

name: Sud Web 2016
description: Deux journées pour faire le plein d'inspiration, les 27 et 28 mai 2016 à Bordeaux.
logo: logo-sud-web.png
locale: fr
url: http://sudweb.fr/2016

# Services configuration
analytics:
  google :
    tracking_id : "UA-22076213-1"

newsletter:
  url: http://sudweb.us2.list-manage.com/subscribe?u=af19b58cf514c01eca3f7652e&id=b579f5b507

# Jekyll configuration

permalink: /:title/
paginate: 5
timezone: Europe/Paris
sass:
    sass_dir: _sass

collections:
  talks:
    output: true
    order: date asc
    permalink: /talks/:path/

exclude: [Gemfile, Gemfile.lock, Procfile, vendor, gems]

gems:
- jekyll-sitemap
